### PR TITLE
Fix serialisation problem with return codes when used with flask-restful

### PR DESCRIPTION
**Pull request by AdamLeyshon**
by using the unpacked status in the tuple tuple or default to 200.

Then return a tuple consisting only of the response object allowing
flask-restful to unpack and serialise the response properly.

I believe this will still work for people without flask-restful too.
All the tests in the suite passed.

### CODE REVIEW

**Comment by AdamLeyshon** [comment]
Should fix #98 and #93

**Comment by westhyena** [comment]
merge this please!

**Comment by thuitaw** [comment]
@jmcarp , any chance we can get this merged?

**Comment by AdamLeyshon** [comment]
Pretty sure this project is considered dead at this point, there has been very little activity here and with flask-restful for a long time.

I'm in the process of converting my projects over to flask-restx.

**Pull request merged**
