### PR TITLE
Fix wrapping of data parsed by schema with `many=True`

### PR DESCRIPTION
**Pull request by decaz**

### CODE REVIEW

**Comment by decaz** [comment]
@sloria there something wrong with installation of `six` at the Travis's Python 3.4 jobs =/

**Comment by sloria** [comment]
The builds should be fixed by cebecf1

**Comment by decaz** [comment]
@sloria thanks! I have rebased commit, but CI still fails.

**Comment by sloria** [comment]
@decaz Sorry about that! It should be fixed now.

**Comment by decaz** [comment]
@sloria any thoughts about this fix? It's related to https://github.com/marshmallow-code/apispec/pull/156.

**Comment by decaz** [comment]
@sloria ping :)

**Comment by sloria** [comment]
Sorry for the delay. Looks good!

**Pull request merged**
