### PR TITLE
Support to query params and header params

### PR DESCRIPTION
**Pull request by rodjjo**
Simple way to add query params and header params

I need Authorization header param (OAUTH2).

Like Authorization: Bearer <bearer_token_value>

image

### CODE REVIEW

**Comment by rodjjo** [comment]
Thanks for the library

**Comment by rodjjo** [comment]
@sloria @jmcarp 

no one can help me with this pull request ?

**Comment by sloria** [comment]
I think this is good to merge. @rodjjo Would you have time to squash your commits? If you don't know how or don't have time, don't worry about it.

**Comment by rodjjo** [comment]
@sloria i combined all my changes into [c1e0d4d](https://github.com/jmcarp/flask-apispec/pull/32/commits/c1e0d4d8ef85b5aec1e9f7c9a71d0ead01d4354d)

**Comment by sloria** [comment]
Thanks @rodjjo

**Comment by adelavega** [comment]
@rodjjo how do I actually add this to a route? Using the `doc` decorator? Do you have an example of how to use this?

**Comment by rodjjo** [comment]
@adelavega you can use "in" like:
image

**Pull request merged**
